const EX={
pushup:['Flexiones','Pectoral · tríceps · deltoides anterior · core','Manos algo más anchas que los hombros. Cuerpo en bloque, abdomen y glúteos activos. Baja controladamente y empuja manteniendo el tronco alineado.','Si cuesta: manos elevadas. Progresión: inclinadas → normales → pies elevados. Evita que la zona lumbar se hunda.','push up proper form'],
invrow:['Remo invertido','Dorsal · romboides · trapecio · bíceps','Cuerpo recto bajo la barra/TRX. Lleva el pecho hacia el apoyo mediante flexión de codos y retracción escapular.','Cuanto más horizontal, más difícil. Mantén pelvis y columna estables.','inverted row proper form'],
split:['Split squat','Cuádriceps · glúteos · isquios','Un pie delante y otro atrás. Desciende controladamente manteniendo el peso principalmente en la pierna delantera y vuelve a subir.','Rodilla y pie estables. Tronco controlado y recorrido sin compensaciones.','split squat proper form'],
squat:['Sentadilla a banco','Cuádriceps · glúteos','Lleva la cadera atrás, toca el banco de forma controlada y vuelve a extender cadera y rodillas.','Usa una altura que permita controlar pelvis y zona lumbar. No te dejes caer.','bench squat proper form'],
step:['Step-up','Glúteos · cuádriceps','Sube a un cajón o banco estable apoyando el pie de trabajo. Empuja con esa pierna y baja lentamente.','Evita impulsarte con la pierna que queda abajo. Controla la bajada.','step up exercise proper form'],
bridge:['Puente de glúteos','Glúteo mayor · isquios','Tumbado boca arriba, rodillas flexionadas. Eleva la pelvis contrayendo los glúteos y vuelve lentamente.','Piensa en extensión de cadera, no en arquear la zona lumbar.','glute bridge proper form'],
chest:['Press de pecho en máquina','Pectoral · tríceps · deltoides anterior','Espalda apoyada y asas a una altura cómoda. Empuja hacia delante sin perder el apoyo del tronco y vuelve controladamente.','Evita un arco lumbar exagerado.','machine chest press proper form'],
pulldown:['Jalón al pecho','Dorsal · bíceps · musculatura escapular','Estabiliza el tronco y lleva la barra hacia la parte alta del pecho mediante flexión de codos y descenso de hombros.','No lleves la barra detrás de la nuca ni te balancees.','lat pulldown proper form'],
row:['Remo con apoyo de pecho','Dorsal · romboides · trapecio · bíceps','Apoya el pecho en la máquina y tira de las asas hacia el torso manteniendo el tronco estable.','El apoyo reduce la demanda lumbar. Controla la vuelta.','chest supported row proper form'],
lateral:['Elevación lateral','Deltoides lateral','Con máquina o cable, separa los brazos lateralmente con carga ligera y vuelve controladamente.','Sin balanceo. Mantén cuello y hombros relajados.','machine lateral raise proper form'],
triceps:['Extensión de tríceps en polea','Tríceps','Codos cerca del cuerpo. Extiende el codo hacia abajo y vuelve controladamente.','No uses el torso para generar impulso.','cable triceps pushdown proper form'],
biceps:['Curl de bíceps en máquina/polea','Bíceps · braquial','Mantén los codos relativamente fijos y flexiona el codo acercando la mano al hombro.','Evita balancearte y controla la bajada.','cable biceps curl proper form'],
legpress:['Prensa de piernas','Cuádriceps · glúteos','Espalda y pelvis apoyadas. Flexiona rodillas y caderas dentro de un rango que mantenga el control pélvico.','No profundices hasta que la pelvis se despegue o la zona lumbar se redondee claramente.','leg press proper form'],
curl:['Curl femoral','Isquiosurales','Ajusta el eje de la máquina y flexiona las rodillas llevando el rodillo hacia ti.','Movimiento controlado, sin rebotes.','leg curl machine proper form'],
hipthrust:['Hip thrust / máquina de glúteo','Glúteo mayor','Extiende la cadera hasta quedar alineado, contrayendo el glúteo al final.','Evita buscar el final mediante hiperextensión lumbar.','hip thrust proper form'],
extension:['Extensión de rodilla','Cuádriceps','Ajusta el eje de la máquina a la rodilla y extiende de forma controlada.','No uses inercia; controla la vuelta.','leg extension machine proper form'],
abductor:['Abductora','Glúteo medio · abductores','Empuja las piernas hacia fuera y vuelve lentamente al punto inicial.','Mantén la pelvis estable y no hagas rebotes.','hip abductor machine proper form'],
calf:['Gemelo en máquina','Gastrocnemio · sóleo','Sube los talones mediante flexión plantar y desciende controladamente.','Recorrido cómodo y sin rebotes.','calf raise machine proper form'],
deadbug:['Dead bug','Core · control lumbopélvico','Tumbado boca arriba, brazos y piernas elevados. Extiende brazo y pierna contrarios sin perder la posición estable de la pelvis.','Si la zona lumbar se arquea, reduce el recorrido.','dead bug exercise proper form'],
pallof:['Pallof press','Core · oblicuos · anti-rotación','De pie junto a una polea, sostén el agarre delante del pecho y extiende los brazos resistiendo la rotación.','La pelvis y el tórax miran al frente.','Pallof press proper form'],
sideplank:['Plancha lateral','Oblicuos · cuadrado lumbar · glúteo medio','Apóyate sobre antebrazo y lateral del pie/rodilla. Eleva la pelvis y mantén cabeza, tronco y cadera alineados.','Empieza con 20–30 s por lado si es necesario. Evita dejar caer la cadera.','side plank proper form']};

const plans={A:[['chest','Press de pecho en máquina','3×10–12'],['pulldown','Jalón al pecho','3×10–12'],['row','Remo con apoyo de pecho','3×10–12'],['pushup','Flexiones','2×8–15'],['lateral','Elevación lateral','3×12–15'],['triceps','Tríceps en polea','2×12–15'],['biceps','Curl de bíceps','2×12–15'],['deadbug','Dead bug','3×8–10/lado']],B:[['legpress','Prensa de piernas','3×10–15'],['split','Split squat','3×8–12/lado'],['curl','Curl femoral','3×10–15'],['hipthrust','Hip thrust / glúteo','3×10–15'],['extension','Extensión de rodilla','2×12–15'],['abductor','Abductora','2×15–20'],['calf','Gemelo en máquina','3×12–20'],['pallof','Pallof press','3×10–12/lado']],C:[['row','Remo con apoyo de pecho','3×10–12'],['chest','Press de pecho en máquina','3×10–12'],['squat','Sentadilla a banco','3×12–15'],['pulldown','Jalón al pecho','3×10–12'],['step','Step-up','2×10/lado'],['lateral','Elevación lateral','2×15'],['bridge','Puente de glúteos','2×15–20'],['sideplank','Plancha lateral','2–3×20–40 s/lado']]};
const schedule=[['Lunes','Fuerza A','A'],['Martes','Natación','SWIM'],['Miércoles','Fuerza B','B'],['Jueves','Descanso + caminar','REST'],['Viernes','Fuerza C','C'],['Sábado','Natación opcional','SWIMOPT'],['Domingo','Descanso','REST']];
let week=Number(localStorage.getItem('fit_week')||1),selected=null,data=JSON.parse(localStorage.getItem('fit_data')||'{"days":{},"logs":{},"weights":[]}');
const phase=w=>w<=4?{name:'Adaptación',sets:'2–3 series',reps:'10–15',rir:'RIR 3',swim:'30–40 min',steps:'≈8.000/día'}:w<=8?{name:'Progresión',sets:'3 series',reps:'8–12 principales',rir:'RIR 2',swim:'40–45 min',steps:'≈9.000/día'}:{name:'Definición / consolidación',sets:'3 principales · 2–3 accesorios',reps:'8–12 principales · 12–15 accesorios',rir:'RIR 1–2',swim:'45–50 min',steps:'9.500–10.000/día'};
const key=(w,d)=>`${w}-${d}`;function save(){localStorage.setItem('fit_data',JSON.stringify(data))}
function completedCount(){return Object.values(data.days||{}).filter(Boolean).length}
function weekCount(w){return schedule.filter(x=>data.days[key(w,x[0])]).length}
function pct(n,d){return d?Math.round(n/d*100):0}
function render(){week=Math.max(1,Math.min(12,week));localStorage.setItem('fit_week',week);document.getElementById('week').value=week;const p=phase(week),c=document.getElementById('content');c.innerHTML=`<div class="card" style="margin-top:10px"><b>${p.name}</b><div class="note" style="margin-top:4px">${p.sets} · ${p.reps} · ${p.rir} · natación ${p.swim} · ${p.steps}</div></div>`;schedule.forEach(([day,title,type])=>{let body='';if('ABC'.includes(type))body=plans[type].map((e,i)=>`<div class="exercise" data-ex="${e[0]}"><div class="num">${i+1}</div><div class="exmain"><div class="exname">${e[1]}</div><div class="pres">${e[2]}</div></div><div class="chev">›</div></div>`).join('');else if(type==='SWIM')body=`<div class="exercise"><div class="num">🏊</div><div class="exmain"><div class="exname">Natación</div><div class="pres">${p.swim} · crawl + espalda · intensidad moderada</div></div></div>`;else if(type==='SWIMOPT')body=`<div class="exercise"><div class="num">🏊</div><div class="exmain"><div class="exname">Natación opcional</div><div class="pres">30–45 min suave · según recuperación</div></div></div>`;else body=`<div class="exercise"><div class="num">✓</div><div class="exmain"><div class="exname">${day==='Jueves'?'Descanso + caminar':'Descanso'}</div><div class="pres">${day==='Jueves'?p.steps+' como referencia diaria':'Recuperación'}</div></div></div>`;let done=!!data.days[key(week,day)];c.innerHTML+=`<div class="day"><div class="dayhead"><div><div class="daytitle">${day} · ${title}</div><div class="meta">${'ABC'.includes(type)?'Toca un ejercicio para ver técnica y registrar carga.':''}</div></div><button class="done ${done?'yes':''}" data-day="${day}">${done?'✓ Hecho':'Marcar'}</button></div>${body}</div>`});c.querySelectorAll('.done').forEach(b=>b.onclick=()=>{const k=key(week,b.dataset.day);data.days[k]=!data.days[k];save();render();summary();dashboard()});c.querySelectorAll('[data-ex]').forEach(e=>e.onclick=()=>openEx(e.dataset.ex));updateProgress();dashboard()}
function updateProgress(){const n=weekCount(week),p=pct(n,7);document.getElementById('pct').textContent=p+'%';document.getElementById('bar').style.width=p+'%'}
function openEx(id){selected=id;const e=EX[id];document.getElementById('mt').textContent=e[0];document.getElementById('mm').textContent=e[1];document.getElementById('mh').textContent=e[2];document.getElementById('mk').textContent=e[3];document.getElementById('video').href='https://www.youtube.com/results?search_query='+encodeURIComponent(e[4]);const l=data.logs[`${week}-${id}`]||{};document.getElementById('ls').value=l.sets||'';document.getElementById('lr').value=l.reps||'';document.getElementById('ll').value=l.load||'';document.getElementById('ln').value=l.notes||'';document.getElementById('modal').classList.add('open')}
function summary(){document.getElementById('summary').innerHTML=Array.from({length:12},(_,i)=>i+1).map(w=>{const n=weekCount(w),p=pct(n,7);return `<div class="card" style="margin:8px 0"><div class="row" style="font-size:13px;font-weight:800"><span>Semana ${w}</span><span>${n}/7</span></div><div class="progress" style="margin-top:8px"><span style="width:${p}%"></span></div></div>`}).join('')}
function weights(){const a=data.weights||[],box=document.getElementById('weights');if(!a.length){box.innerHTML='<div class="note">Todavía no hay registros.</div>';document.getElementById('avg').value='—';return}const v=a.slice(-7).map(x=>x.value);document.getElementById('avg').value=(v.reduce((x,y)=>x+y,0)/v.length).toFixed(1);box.innerHTML=a.slice().reverse().slice(0,10).map(x=>`<div class="row" style="padding:7px 0;border-bottom:1px solid var(--line);font-size:13px"><span>${new Date(x.date).toLocaleDateString('es-ES')}</span><b>${x.value.toFixed(1)} kg</b></div>`).join('')}

function dashboard(){
  const done=completedCount(), global=pct(done,84), wc=weekCount(week), wp=pct(wc,7), a=data.weights||[], latest=a.length?a[a.length-1].value:null, first=a.length?a[0].value:null;
  document.getElementById('dashPhase').textContent=phase(week).name;
  document.getElementById('dashWeek').textContent=`${week} / 12`;
  document.getElementById('dashWeekSub').textContent=`${wp}% completada`;
  document.getElementById('dashCompletion').textContent=global+'%';
  document.getElementById('dashCompletionSub').textContent=`${done} de 84 días`;
  document.getElementById('globalPct').textContent=global+'%';document.getElementById('globalBar').style.width=global+'%';
  if(latest!==null){document.getElementById('dashWeight').textContent=latest.toFixed(1)+' kg';document.getElementById('dashWeightSub').textContent=`Objetivo 63 kg · ${latest>63?'−'+(latest-63).toFixed(1):'objetivo alcanzado'}`;document.getElementById('dashToGoal').textContent=latest>63?`Faltan ${(latest-63).toFixed(1)} kg`:'Objetivo alcanzado'}else{document.getElementById('dashWeight').textContent='—';document.getElementById('dashWeightSub').textContent='Añade tu primer peso';document.getElementById('dashToGoal').textContent='Desde 70 kg'}
  if(first!==null&&latest!==null){const diff=latest-first;document.getElementById('weightDelta').textContent=(diff<0?'↓ ':'↑ ')+Math.abs(diff).toFixed(1)+' kg desde el primer registro';document.getElementById('weightDelta').className='delta '+(diff<=0?'good':'')}
  else document.getElementById('weightDelta').textContent='Registra 2+ pesos para ver tendencia';
  renderCalendar();renderNext();renderWeightChart();
}
function renderCalendar(){const days=['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'];document.getElementById('calendar').innerHTML=Array.from({length:12},(_,i)=>{const w=i+1;return `<div class="cal-row tap" data-calweek="${w}"><div class="cal-week">Sem. ${w}</div>${days.map(d=>{const type=schedule.find(x=>x[0]===d)[2],done=!!data.days[key(w,d)], active=['A','B','C','SWIM'].includes(type),rest=['REST','SWIMOPT'].includes(type);return `<div class="cal-day ${done?'done':active?'active':'rest'} ${w===week?'todayweek':''}" title="${d}">${done?'✓':active?'•':''}</div>`}).join('')}</div>`}).join('');document.querySelectorAll('[data-calweek]').forEach(el=>el.onclick=()=>{week=+el.dataset.calweek;activateTab('plan');render()})}
function renderNext(){const idx=schedule.findIndex(x=>!data.days[key(week,x[0])]);const item=schedule[idx<0?0:idx];const [day,title,type]=item;const icon=type==='SWIM'||type==='SWIMOPT'?'🏊':type==='REST'?'◷':'🏋️';const status=idx<0?'Semana completada · puedes recuperar o revisar registros':`${day} · ${title}`;document.getElementById('nextSession').innerHTML=`<div class="next-icon">${icon}</div><div><div class="next-name">${idx<0?'¡Semana completada!':title}</div><div class="next-meta">${status}</div></div>`}
function renderWeightChart(){const box=document.getElementById('weightChart'),a=(data.weights||[]).slice(-10);if(a.length<2){box.innerHTML='<div class="chart-empty">Introduce al menos 2 registros de peso para ver la evolución.</div>';return}const vals=a.map(x=>x.value),min=Math.min(63,...vals)-.5,max=Math.max(...vals)+.5,w=330,h=105,pad=12,usableW=w-pad*2,usableH=h-pad*2;const pts=vals.map((v,i)=>{const x=pad+(i/(vals.length-1))*usableW,y=pad+(1-(v-min)/(max-min))*usableH;return [x,y]});const path=pts.map((p,i)=>(i?'L':'M')+p[0].toFixed(1)+' '+p[1].toFixed(1)).join(' ');const goalY=pad+(1-(63-min)/(max-min))*usableH;box.innerHTML=`<svg class="mini-chart" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" aria-label="Evolución del peso"><line class="target-line" x1="${pad}" y1="${goalY}" x2="${w-pad}" y2="${goalY}"/><path class="chart-line" d="${path}"/>${pts.map(p=>`<circle class="chart-dot" cx="${p[0]}" cy="${p[1]}" r="3.2"/>`).join('')}<text class="chart-label" x="${pad}" y="${h-2}">${new Date(a[0].date).toLocaleDateString('es-ES',{day:'2-digit',month:'2-digit'})}</text><text class="chart-label" x="${w-pad}" y="${h-2}" text-anchor="end">${new Date(a[a.length-1].date).toLocaleDateString('es-ES',{day:'2-digit',month:'2-digit'})}</text><text class="chart-label" x="${w-pad-2}" y="${goalY-4}" text-anchor="end">63 kg</text></svg>`}
function activateTab(name){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id===name));if(name==='seguimiento')summary();if(name==='inicio')dashboard()}

document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>activateTab(t.dataset.tab));
document.getElementById('week').innerHTML=Array.from({length:12},(_,i)=>`<option value="${i+1}">Semana ${i+1}</option>`).join('');
document.getElementById('week').onchange=e=>{week=+e.target.value;render()};document.getElementById('prev').onclick=()=>{week--;render()};document.getElementById('next').onclick=()=>{week++;render()};
document.getElementById('close').onclick=()=>document.getElementById('modal').classList.remove('open');document.getElementById('modal').onclick=e=>{if(e.target.id==='modal')document.getElementById('modal').classList.remove('open')};
document.getElementById('saveLog').onclick=()=>{if(!selected)return;data.logs[`${week}-${selected}`]={sets:document.getElementById('ls').value,reps:document.getElementById('lr').value,load:document.getElementById('ll').value,notes:document.getElementById('ln').value,date:new Date().toISOString()};save();document.getElementById('modal').classList.remove('open')};
document.getElementById('saveWeight').onclick=()=>{const v=+document.getElementById('weight').value;if(!Number.isFinite(v)||v<=0)return;(data.weights??=[]).push({date:new Date().toISOString(),value:v});save();weights();document.getElementById('weight').value='';dashboard()};
document.getElementById('export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='seguimiento_entrenamiento.json';a.click()};
document.getElementById('reset').onclick=()=>{if(confirm('¿Borrar todo el seguimiento de este dispositivo?')){data={days:{},logs:{},weights:[]};save();render();weights();summary();dashboard()}};
render();weights();summary();dashboard();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
